package com.crdb.microbatch.service;

import com.crdb.microbatch.repository.TestInsertRepository;
import com.crdb.microbatch.task.CrdbInsertTask;
import com.vajrapulse.api.LoadPattern;
import com.vajrapulse.api.StaticLoad;
import com.vajrapulse.api.TaskIdentity;
import com.vajrapulse.exporter.otel.OpenTelemetryExporter;
import com.vajrapulse.exporter.otel.OpenTelemetryExporter.Protocol;
import com.vajrapulse.exporter.report.HtmlReportExporter;
import com.vajrapulse.worker.pipeline.MetricsPipeline;
import io.micrometer.core.instrument.MeterRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Service;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Duration;
import java.util.Map;

/**
 * Service that orchestrates the load test execution using VajraPulse MetricsPipeline.
 * 
 * <p>Runs a static load test at 10,000 TPS for 2 minutes.
 * Metrics are exported to OpenTelemetry collector every 10 seconds.
 * HTML report is automatically generated by HtmlReportExporter.
 */
@Service
public class LoadTestService implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(LoadTestService.class);
    
    private static final Duration TEST_DURATION = Duration.ofMinutes(2);
    private static final int EXPORT_INTERVAL_SECONDS = 10;
    private static final String OTLP_ENDPOINT = "http://localhost:4317";
    private static final String REPORT_DIR = "reports";
    private static final String REPORT_FILE = "crdb-microbatch-load-test-report.html";
    
    private final CrdbInsertTask task;
    private final TestInsertRepository repository;
    private final MeterRegistry meterRegistry;
    
    // Store result from pipeline.run() - type is inferred from pipeline.run() return type
    private Object testResult;
    private volatile boolean testCompleted = false;

    /**
     * Constructor for LoadTestService.
     * 
     * @param task the CRDB insert task
     * @param repository the test insert repository
     * @param meterRegistry the Micrometer registry for metrics
     */
    public LoadTestService(CrdbInsertTask task, TestInsertRepository repository, MeterRegistry meterRegistry) {
        this.task = task;
        this.repository = repository;
        this.meterRegistry = meterRegistry;
        registerShutdownHook();
    }

    /**
     * Registers a JVM shutdown hook to ensure final reports are generated.
     */
    private void registerShutdownHook() {
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            if (!testCompleted) {
                log.warn("=== Shutdown detected - Generating final report ===");
                generateFinalReport(testResult);
            }
        }, "load-test-shutdown-hook"));
    }

    @Override
    public void run(String... args) throws Exception {
        log.info("=== Starting CRDB Microbatch Load Test ===");
        log.info("Duration: {} minutes", TEST_DURATION.toMinutes());
        
        initializeDatabase();
        task.init();
        
        TaskIdentity identity = createTaskIdentity();
        OpenTelemetryExporter otelExporter = createOpenTelemetryExporter(identity);
        HtmlReportExporter htmlExporter = createHtmlReportExporter();
        
        executeLoadTest(otelExporter, htmlExporter);
        
        task.teardown();
        
        long finalCount = repository.getCount();
        log.info("=== Load Test Complete ===");
        log.info("Final row count: {}", finalCount);
    }
    
    /**
     * Initializes the database by clearing existing data.
     * 
     * <p>Uses DROP/CREATE for speed (faster than TRUNCATE for large tables).
     */
    private void initializeDatabase() {
        try {
            long existingCount = repository.getCount();
            if (existingCount > 0) {
                log.info("Found {} existing rows, dropping and recreating table...", existingCount);
                repository.dropAndRecreateTable();
                log.info("Table recreated successfully");
            } else {
                log.info("Table is empty, no cleanup needed");
            }
        } catch (Exception e) {
            log.error("Failed to initialize database", e);
            throw new RuntimeException("Database initialization failed", e);
        }
    }


    /**
     * Creates task identity for observability tagging.
     * 
     * @return the task identity
     */
    private TaskIdentity createTaskIdentity() {
        return new TaskIdentity(
            "crdb-insert-load-test",
            Map.of(
                "scenario", "microbatch-performance",
                "component", "cockroachdb-insert",
                "database", "cockroachdb"
            )
        );
    }

    /**
     * Creates and configures the OpenTelemetry exporter.
     * 
     * @param identity the task identity
     * @return the configured exporter
     */
    private OpenTelemetryExporter createOpenTelemetryExporter(TaskIdentity identity) {
        return OpenTelemetryExporter.builder()
            .endpoint(OTLP_ENDPOINT)
            .protocol(Protocol.GRPC)
            .exportInterval(EXPORT_INTERVAL_SECONDS)
            .taskIdentity(identity)
            .resourceAttributes(createResourceAttributes())
            .build();
    }

    /**
     * Creates resource attributes for OpenTelemetry.
     * 
     * @return map of resource attributes
     */
    private Map<String, String> createResourceAttributes() {
        return Map.of(
            "service.name", "crdb-microbatch-load-test",
            "service.version", "1.0.0",
            "environment", "test",
            "test.type", "microbatch-performance",
            "database", "cockroachdb"
        );
    }


    /**
     * Creates and configures the HTML report exporter.
     * 
     * @return the configured HTML report exporter
     */
    private HtmlReportExporter createHtmlReportExporter() {
        Path reportPath = Paths.get(REPORT_DIR, REPORT_FILE);
        return new HtmlReportExporter(reportPath, meterRegistry);
    }

    /**
     * Executes the load test using MetricsPipeline with StaticLoad.
     * 
     * <p>Uses StaticLoad at 10000 TPS for 2 minutes to test batching performance.
     * Metrics are exported to both OpenTelemetry collector and HTML report.
     * 
     * <p>Note: Limited by connection pool capacity (10 connections). Backpressure
     * implementation is needed to scale beyond this limit (tabled for later).
     * 
     * @param otelExporter the OpenTelemetry exporter
     * @param htmlExporter the HTML report exporter
     * @throws Exception if execution fails
     */
    private void executeLoadTest(OpenTelemetryExporter otelExporter, HtmlReportExporter htmlExporter) 
            throws Exception {
        try (MetricsPipeline pipeline = createMetricsPipeline(otelExporter, htmlExporter)) {
            // Use StaticLoad at 10000 TPS for 2 minutes
            // Note: Limited by connection pool capacity (10 connections)
            // Backpressure implementation needed for higher TPS (tabled for later)
            LoadPattern loadPattern = new StaticLoad(10000.0, TEST_DURATION);
            
            log.info("=== Starting Static Load Test ===");
            log.info("Load Pattern: {}", loadPattern);
            log.info("TPS: 10,000");
            log.info("Test Duration: {} minutes", TEST_DURATION.toMinutes());
            log.info("Goal: Test batching performance at sustained 10000 TPS for 2 minutes");
            log.info("Note: Limited by connection pool (10 connections) - backpressure needed for higher TPS");
            log.info("Reports: HTML report will be generated at {}/{}", REPORT_DIR, REPORT_FILE);
            
            // Start pipeline execution
            var result = pipeline.run(task, loadPattern);
            testResult = result;
            testCompleted = true;
            
            // Use result directly - no reflection needed since we have the typed variable
            log.info("=== Load Test Complete ===");
            log.info("Final metrics - Total executions: {}, Success: {}, Failures: {}, Success rate: {:.2f}%",
                result.totalExecutions(), result.successCount(), result.failureCount(),
                result.totalExecutions() > 0 ? result.successRate() * 100.0 : 0.0);
            
            // Generate final reports (pass typed result to avoid reflection)
            generateFinalReport(result);
        }
    }

    /**
     * Creates the metrics pipeline with exporters (OpenTelemetry and HTML).
     * 
     * @param otelExporter the OpenTelemetry exporter
     * @param htmlExporter the HTML report exporter
     * @return the configured pipeline
     */
    private MetricsPipeline createMetricsPipeline(OpenTelemetryExporter otelExporter, HtmlReportExporter htmlExporter) {
        return MetricsPipeline.builder()
            .addExporter(otelExporter)
            .addExporter(htmlExporter)
            .withRunId(otelExporter.getRunId())
            .withPeriodic(Duration.ofSeconds(EXPORT_INTERVAL_SECONDS))
            .withPercentiles(0.5, 0.9, 0.95, 0.99)
            .build();
    }

    /**
     * Generates final report with test results and metrics summary.
     * 
     * <p>Note: HTML report is automatically generated by HtmlReportExporter.
     * This method only prints console summary.
     * 
     * @param result the pipeline execution result (can be null from shutdown hook)
     */
    private void generateFinalReport(Object result) {
        try {
            long finalCount = repository.getCount();
            printFinalSummary(finalCount, result);
            log.info("HTML report generated by VajraPulse HtmlReportExporter: {}/{}", REPORT_DIR, REPORT_FILE);
        } catch (Exception e) {
            log.error("Failed to generate final report", e);
        }
    }

    /**
     * Prints final summary to console.
     * 
     * @param finalCount the final row count
     * @param result the pipeline execution result (can be null from shutdown hook)
     */
    private void printFinalSummary(long finalCount, Object result) {
        log.info("========================================");
        log.info("=== FINAL TEST SUMMARY ===");
        log.info("========================================");
        log.info("Test Duration: {} minutes", TEST_DURATION.toMinutes());
        log.info("Final Row Count: {}", finalCount);
        
        if (result != null) {
            try {
                // Use reflection only when result type is truly unknown (e.g., from shutdown hook)
                var totalExecutions = (long) result.getClass().getMethod("totalExecutions").invoke(result);
                var successCount = (long) result.getClass().getMethod("successCount").invoke(result);
                var failureCount = (long) result.getClass().getMethod("failureCount").invoke(result);
                var successRate = (double) result.getClass().getMethod("successRate").invoke(result);
                
                log.info("Total Executions: {}", totalExecutions);
                log.info("Successful: {}", successCount);
                log.info("Failed: {}", failureCount);
                log.info("Success Rate: {:.2f}%", successRate * 100.0);
                log.info("Average Throughput: {:.2f} ops/sec",
                    totalExecutions > 0 ? (double) totalExecutions / TEST_DURATION.getSeconds() : 0.0);
            } catch (Exception e) {
                log.warn("Could not extract test result metrics: {}", e.getMessage());
            }
        }
        
        log.info("========================================");
    }


}
